# -*- coding: utf-8 -*-
"""
Checks for tools/mps_axoplasm.py: placing a widefield betaIII-tubulin image
on the localizations, the axoplasm mask, and the membrane/interior
classification.

Synthetic images with a known answer, plus the April 2026 ROI 1 data when
it is present (its widefield images sit (-2.05, +5.55) px from the STORM
localizations).

Run:  python validate_axoplasm.py
"""

from __future__ import annotations

import json
import logging
import math
import os
import shutil
import sys
import tempfile
import traceback
from typing import List, Tuple

import numpy as np
from scipy import ndimage

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from tools import mps_axoplasm as ax  # noqa: E402

# The synthetic stacks carry Micro-Manager's plane metadata but not the
# header Micro-Manager writes at the start of its files, and tifffile logs
# that it cannot read that header. Real Micro-Manager files read cleanly.
logging.getLogger("tifffile").setLevel(logging.ERROR)

PASSED = 0
FAILED = 0
PIXEL_NM = 113.0

DATA = os.environ.get("MPS_AXOPLASM_DATA", r"C:\Users\nicol\OneDrive\Doctorado")
APRIL_FULL = os.path.join(
    DATA, "30.4.26", "26.04.30_bIIspt_50ms_90mW_TIRF_3con5_1",
    "26.04.30_bIIspt_RCC1000_filt_lpxy015_z400.hdf5")
APRIL_SPEC = os.path.join(DATA, "30.4.26", "WF_spec_1",
                          "WF_spec_1_MMStack.ome.tif")
APRIL_TUB = os.path.join(DATA, "30.4.26", "WF_tub_1", "WF_tub_1_MMStack.ome.tif")
APRIL_AXON7 = os.path.join(
    DATA, "1°Reunión de avances de tesis", "Abril", "ROI 1", "Axon 7",
    "26.04.30_bIIspt_50ms_90mW_TIRF_3con5_1_MMStack.ome_locs_filter_render_"
    "byRCC1000_picked_axon7.hdf5")


def check(name: str, fn) -> None:
    global PASSED, FAILED
    try:
        detail = fn()
    except Exception:  # noqa: BLE001 - a harness
        FAILED += 1
        print(f"  FAIL  {name}")
        for line in traceback.format_exc().strip().splitlines()[-3:]:
            print(f"        {line}")
        return
    PASSED += 1
    print(f"  ok    {name}" + (f"   [{detail}]" if detail else ""))


def expect_error(fn, *words: str) -> str:
    try:
        fn()
    except ValueError as error:
        text = str(error)
        for word in words:
            assert word in text, (word, text)
        return text
    raise AssertionError("no error raised")


def movie_info(region: str = "224-222-274-310", binning: object = 2,
               movie: str = "movie.ome.tif") -> List[dict]:
    return [{"Micro-Manager Metadata": {"ROI": region, "Binning": binning},
             "File": movie},
            {"Generated by": "Picasso Localize", "Pixelsize": PIXEL_NM}]


def ring_field(rng: np.random.Generator, shape: Tuple[int, int],
               n_rings: int = 14) -> List[Tuple[float, float, float]]:
    rows, cols = shape
    rings: List[Tuple[float, float, float]] = []
    while len(rings) < n_rings:
        r = rng.uniform(4, 10)
        cx, cy = rng.uniform(r + 3, cols - r - 3), rng.uniform(r + 3, rows - r - 3)
        if all(math.hypot(cx - a, cy - b) > r + s + 3 for a, b, s in rings):
            rings.append((cx, cy, r))
    return rings


def sample_rings(rng: np.random.Generator, rings, per_ring: int = 3000
                 ) -> Tuple[np.ndarray, np.ndarray]:
    xs, ys = [], []
    for cx, cy, r in rings:
        angle = rng.uniform(0, 2 * np.pi, per_ring)
        radial = r + rng.normal(0, 0.25, per_ring)
        xs.append(cx + radial * np.cos(angle))
        ys.append(cy + radial * np.sin(angle))
    return np.concatenate(xs), np.concatenate(ys)


def widefield_of(rng, rings, shape, shift=(0.0, 0.0), noise=3.0):
    """A widefield image of the rings, as seen ``shift`` px away."""
    x, y = sample_rings(rng, rings, per_ring=6000)
    counts = ax.render_counts(x + shift[0], y + shift[1], shape)
    image = ndimage.gaussian_filter(counts, 1.3) * 5.0 + 100.0
    return image + rng.normal(0, noise, shape)


def disc_image(shape, centre, radius, value=100.0, background=10.0):
    """
    A disc with a one-pixel linear edge, so that its half-intensity
    contour is the circle of ``radius`` at every angle. A hard-edged disc
    is a staircase, half a pixel inside the circle on the diagonals.
    """
    rows, cols = shape
    rr, cc = np.mgrid[0:rows, 0:cols]
    d = np.hypot(cc - centre[0], rr - centre[1])
    weight = np.clip(0.5 + (radius - d), 0.0, 1.0)
    return background + (value - background) * weight


def half_level(value=100.0, background=10.0):
    return 0.5 * (value + background)


# ============================================================== loading
def test_loading() -> None:
    print("\n1. READING THE WIDEFIELD IMAGE")
    import tifffile

    tmp = tempfile.mkdtemp(prefix="axoplasm_io_")

    def mm_stack():
        path = os.path.join(tmp, "stack.ome.tif")
        planes = np.stack([np.full((6, 5), v, np.uint16) for v in (10, 20, 60)])
        meta = json.dumps({"ROI": "221-224-5-6", "Binning": "2",
                           "PixelSizeUm": 0.0,
                           "ReceivedTime": "2026-04-30 14:41:15"})
        tifffile.imwrite(path, planes, ome=True, metadata={"axes": "TYX"},
                         extratags=[(51123, "s", 0, meta, True)])
        image = ax.load_widefield(path)
        assert image.shape == (6, 5) and image.n_planes == 3
        assert np.allclose(image.image, 30.0), image.image
        assert image.camera_region == (221, 224, 5, 6)
        assert image.binning == 2 and image.pixel_size_nm is None
        assert image.acquired == "2026-04-30 14:41:15" and not image.notes
        return "3 planes averaged; region, binning and time read"

    def pixel_size_recorded():
        path = os.path.join(tmp, "calibrated.tif")
        meta = json.dumps({"ROI": "0-0-4-4", "PixelSizeUm": 0.065})
        tifffile.imwrite(path, np.zeros((4, 4), np.uint16),
                         extratags=[(51123, "s", 0, meta, True)])
        assert abs(ax.load_widefield(path).pixel_size_nm - 65.0) < 1e-9
        return None

    def plain_tiff():
        path = os.path.join(tmp, "plain.tif")
        tifffile.imwrite(path, np.ones((4, 4), np.uint16))
        image = ax.load_widefield(path)
        assert image.camera_region is None and image.binning is None
        assert image.notes and "no Micro-Manager metadata" in image.notes[0]
        return None

    def channels_refused():
        path = os.path.join(tmp, "two_channels.tif")
        tifffile.imwrite(path, np.zeros((2, 4, 4), np.uint16), imagej=True,
                         metadata={"axes": "CYX"})
        expect_error(lambda: ax.load_widefield(path), "2 channels")
        return None

    try:
        check("a Micro-Manager stack", mm_stack)
        check("a recorded pixel size", pixel_size_recorded)
        check("a TIFF without metadata", plain_tiff)
        check("several channels are refused", channels_refused)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# ============================================================ placing
def test_placing() -> None:
    print("\n2. PLACING THE IMAGE ON THE LOCALIZATIONS")

    def image_with(region, binning=2, pixel=None):
        return ax.WidefieldImage(
            path="tub.tif", image=np.zeros((10, 10)), n_planes=1,
            camera_region=region, binning=binning, pixel_size_nm=pixel,
            acquired=None)

    def offsets():
        (dx, dy), notes = ax.camera_offset(
            image_with((221, 224, 10, 10)), movie_info(), PIXEL_NM)
        assert (dx, dy) == (3.0, -2.0) and not notes, (dx, dy, notes)
        return "movie at (224, 222), image at (221, 224): (+3, -2) px"

    def refusals():
        expect_error(lambda: ax.camera_offset(
            image_with((0, 0, 10, 10), binning=1), movie_info(), PIXEL_NM),
            "binning 1", "binning 2")
        expect_error(lambda: ax.camera_offset(
            image_with((0, 0, 10, 10), pixel=65.0), movie_info(), PIXEL_NM),
            "65", "113")
        return "another binning or pixel size"

    def unknown_region():
        (dx, dy), notes = ax.camera_offset(image_with(None), movie_info(),
                                           PIXEL_NM)
        assert (dx, dy) == (0.0, 0.0) and notes
        (dx, dy), notes = ax.camera_offset(image_with((0, 0, 10, 10)),
                                           [{"Pixelsize": 113}], PIXEL_NM)
        assert (dx, dy) == (0.0, 0.0) and "localization movie" in notes[0]
        return None

    def geometry():
        region, binning, _time, movie = ax.movie_geometry(movie_info(
            binning="2x2"))
        assert region == (224, 222, 274, 310) and binning == 2
        assert movie == "movie.ome.tif"
        assert ax.movie_geometry([{"Pixelsize": 113}]) == (None, None, None,
                                                            None)
        return None

    def pixel_centres():
        # Picasso puts an emitter centred on pixel c at x = c.
        counts = ax.render_counts(np.array([11.0, 11.49, 11.51, -0.49]),
                                  np.array([7.0, 7.0, 7.0, 0.0]), (10, 20))
        assert counts[7, 11] == 2 and counts[7, 12] == 1 and counts[0, 0] == 1
        assert counts.sum() == 4
        return "pixel c spans [c - 0.5, c + 0.5)"

    check("camera regions give the offset", offsets)
    check("another binning or pixel size is refused", refusals)
    check("an unknown region is assumed, and said", unknown_region)
    check("the movie's geometry from Picasso's metadata", geometry)
    check("pixel centres", pixel_centres)


# ========================================================= registration
def test_registration() -> None:
    print("\n3. REGISTERING TO A WIDEFIELD IMAGE OF THE SAME PROTEIN")
    shape = (180, 160)

    def known_shift():
        rng = np.random.default_rng(1)
        rings = ring_field(rng, shape)
        true = (-2.05, 5.55)
        image = widefield_of(rng, rings, shape, shift=true)
        x, y = sample_rings(rng, rings)
        reg = ax.measure_shift(image, x, y)
        err = np.hypot(reg.shift_px[0] - true[0], reg.shift_px[1] - true[1])
        assert err < 0.15, (reg.shift_px, true)
        assert not reg.warnings, reg.warnings
        assert reg.peak > reg.zero and reg.runner_up < 0.5 * reg.peak
        assert reg.score > ax.MIN_REGISTRATION_SCORE, reg.score
        # The shift is what the localizations need: moved by it, they
        # correlate with the image better than by its opposite.
        moved = ax.measure_shift(image, x + reg.shift_px[0],
                                 y + reg.shift_px[1])
        assert np.hypot(*moved.shift_px) < 0.15, moved.shift_px
        return (f"({reg.shift_px[0]:+.2f}, {reg.shift_px[1]:+.2f}) px for "
                f"({true[0]:+.2f}, {true[1]:+.2f}); peak {reg.peak:.2f}, "
                f"unshifted {reg.zero:.2f}, score {reg.score:.0f}")

    def beyond_the_search():
        rng = np.random.default_rng(2)
        rings = ring_field(rng, shape)
        image = widefield_of(rng, rings, shape, shift=(26.0, 0.0))
        x, y = sample_rings(rng, rings)
        reg = ax.measure_shift(image, x, y, max_shift_px=20)
        # A spurious shift inside the search wins; it must not pass as a
        # registration.
        assert reg.warnings, (reg.shift_px, reg.score, reg.runner_up)
        return "flagged: " + reg.warnings[0][:50] + "..."

    def ambiguous_lattice():
        # Identical rings on a regular grid: a shift of one period fits
        # as well as none.
        rng = np.random.default_rng(3)
        rings = [(20.0 + 20 * i, 20.0 + 20 * j, 6.0)
                 for i in range(7) for j in range(8)]
        image = widefield_of(rng, rings, shape)
        x, y = sample_rings(rng, rings, per_ring=800)
        reg = ax.measure_shift(image, x, y, max_shift_px=25)
        assert any("ambiguous" in w for w in reg.warnings), reg.warnings
        return None

    def off_the_image():
        expect_error(lambda: ax.measure_shift(
            np.zeros(shape), np.array([500.0, 600.0]),
            np.array([500.0, 600.0])), "do not fall on")
        return None

    check("a known shift is recovered, with its sign", known_shift)
    check("a shift beyond the search is flagged", beyond_the_search)
    check("a periodic field is flagged as ambiguous", ambiguous_lattice)
    check("localizations off the image are refused", off_the_image)


# ================================================================ mask
def test_mask() -> None:
    print("\n4. THE AXOPLASM MASK")
    shape = (80, 80)

    def otsu():
        rng = np.random.default_rng(4)
        values = np.concatenate([rng.normal(100, 5, 4000),
                                 rng.normal(200, 8, 2500)])
        t = ax.otsu_threshold(values)
        assert 115 < t < 185, t
        # Against a brute-force search over the same histogram.
        hist, edges = np.histogram(values, bins=256)
        centres = 0.5 * (edges[:-1] + edges[1:])
        best, best_t = -1.0, None
        for k in range(1, 256):
            w0, w1 = hist[:k].sum(), hist[k:].sum()
            if w0 == 0 or w1 == 0:
                continue
            m0 = (hist[:k] * centres[:k]).sum() / w0
            m1 = (hist[k:] * centres[k:]).sum() / w1
            score = w0 * w1 * (m0 - m1) ** 2
            if score > best:
                best, best_t = score, edges[k]
        # A flat maximum may be resolved at another bin than the first:
        # compare the variance reached, not the position.
        k = int(np.searchsorted(edges, t))
        w0, w1 = hist[:k].sum(), hist[k:].sum()
        m0 = (hist[:k] * centres[:k]).sum() / w0
        m1 = (hist[k:] * centres[k:]).sum() / w1
        assert abs(w0 * w1 * (m0 - m1) ** 2 / best - 1) < 1e-6, (t, best_t)
        assert ax.otsu_threshold(np.full(10, 7.0)) == 7.0
        # Two levels only: the middle of the gap, not just above the lower.
        two = ax.otsu_threshold(np.array([10.0] * 50 + [100.0] * 20))
        assert 50 < two < 60, two
        return f"{t:.1f} between modes at 100 and 200; {two:.1f} for 10 and 100"

    def disc_and_distances():
        centre, radius = (40.0, 40.0), 12.0
        image = disc_image(shape, centre, radius)
        mask = ax.build_mask(image, centre, radius, PIXEL_NM,
                             threshold=half_level(), smooth_sigma_px=0.0)
        truth = math.pi * (radius * PIXEL_NM / 1000) ** 2
        assert abs(mask.area_um2 / truth - 1) < 0.03, (mask.area_um2, truth)
        assert not mask.warnings, mask.warnings
        angles = np.deg2rad([0, 30, 45, 60, 90, 135, 200, 315])
        worst = 0.0
        for depth in (-8.0, -3.0, 0.0, 6.0, 12.0):
            r = radius - depth
            cols = centre[0] + r * np.cos(angles)
            rows = centre[1] + r * np.sin(angles)
            got = mask.distance_at(cols, rows)
            worst = max(worst, float(np.max(np.abs(got - depth * PIXEL_NM))))
        # EDT on a grid 4x finer than the camera, and a bilinear contour:
        # a third of a camera pixel.
        assert worst < 0.35 * PIXEL_NM, worst
        automatic = ax.build_mask(image, centre, radius, PIXEL_NM,
                                  smooth_sigma_px=0.0)
        assert abs(automatic.area_um2 / truth - 1) < 0.1, automatic.area_um2
        return (f"area within 3%; distances within {worst:.0f} nm at any "
                f"angle; Otsu's mask within 10%")

    def neighbour_left_out():
        # A dim axon, and a brighter neighbour 4 px from its edge.
        centre, radius = (30.0, 40.0), 8.0
        image = disc_image(shape, centre, radius, value=60.0) + \
            disc_image(shape, (47.0, 40.0), 5.0, value=150.0, background=0.0)
        above_axon = ax.build_mask(image, centre, radius, PIXEL_NM,
                                   threshold=100.0, smooth_sigma_px=0.0)
        # Only the neighbour clears the cut, and it is not over the axon.
        assert above_axon.empty, above_axon.area_um2
        assert any("No axoplasm" in w for w in above_axon.warnings)
        manual = ax.build_mask(image, centre, radius, PIXEL_NM,
                               threshold=35.0, smooth_sigma_px=0.0)
        truth = math.pi * (radius * PIXEL_NM / 1000) ** 2
        assert manual.threshold_source == "manual"
        assert abs(manual.area_um2 / truth - 1) < 0.05, manual.area_um2
        # A point on the neighbour, inside the analysed region.
        assert manual.distance_at(np.array([44.0]), np.array([40.0]))[0] < 0
        return "the neighbour is never taken for the axon"

    def holes_filled():
        # A dark centre: the region over the axon is taken instead of the
        # centre's, with a warning, and its hole is filled.
        centre, radius = (40.0, 40.0), 12.0
        image = disc_image(shape, centre, radius) - \
            disc_image(shape, centre, 4.0, value=90.0, background=0.0)
        mask = ax.build_mask(image, centre, radius, PIXEL_NM,
                             threshold=half_level(), smooth_sigma_px=0.0)
        assert any("centre is below" in w for w in mask.warnings), mask.warnings
        assert mask.distance_at(np.array([40.0]), np.array([40.0]))[0] > 0
        return None

    def nothing_over_the_threshold():
        centre, radius = (40.0, 40.0), 12.0
        image = disc_image(shape, centre, radius)
        mask = ax.build_mask(image, centre, radius, PIXEL_NM,
                             threshold=1000.0, smooth_sigma_px=0.0)
        assert mask.empty and any("No axoplasm" in w for w in mask.warnings)
        result = ax.classify(mask, np.array([40.0, 60.0]),
                             np.array([40.0, 40.0]), 0.0)
        assert list(result.labels) == [ax.LABEL_MEMBRANE] * 2
        assert np.all(np.isneginf(result.distance_nm))
        return None

    def area_warnings():
        centre = (40.0, 40.0)
        image = disc_image(shape, centre, 14.0)
        big = ax.build_mask(image, centre, 6.0, PIXEL_NM, smooth_sigma_px=0.0)
        assert any("times the area" in w for w in big.warnings), big.warnings
        small = ax.build_mask(disc_image(shape, centre, 5.0), centre, 12.0,
                              PIXEL_NM, smooth_sigma_px=0.0)
        assert any("only" in w for w in small.warnings), small.warnings
        return None

    def mask_reaches_the_region_edge():
        centre, radius = (40.0, 40.0), 10.0
        image = np.full(shape, 100.0)
        image[:, :20] = 10.0
        mask = ax.build_mask(image, centre, radius, PIXEL_NM,
                             threshold=50.0, smooth_sigma_px=0.0)
        assert any("edge of the analysed region" in w
                   for w in mask.warnings), mask.warnings
        return None

    def axon_outside():
        expect_error(lambda: ax.build_mask(np.zeros(shape), (500.0, 500.0),
                                           5.0, PIXEL_NM), "outside")
        return None

    check("Otsu's threshold", otsu)
    check("a disc: area and signed distances", disc_and_distances)
    check("a brighter neighbour", neighbour_left_out)
    check("holes are filled", holes_filled)
    check("nothing over the threshold", nothing_over_the_threshold)
    check("a mask much larger or smaller than the ring", area_warnings)
    check("a mask cut by the region's edge", mask_reaches_the_region_edge)
    check("an axon off the image", axon_outside)


# ======================================================== classification
def test_classification() -> None:
    print("\n5. MEMBRANE OR INTERIOR")
    shape = (80, 80)
    centre, radius = (40.0, 40.0), 12.0
    mask = ax.build_mask(disc_image(shape, centre, radius), centre, radius,
                         PIXEL_NM, threshold=half_level(),
                         smooth_sigma_px=0.0)

    def margin():
        # Depths of 10, 2, 0.5 px inside, 2 px outside, and one off the
        # region altogether (the edge is 12 px from the centre).
        cols = centre[0] + np.array([2.0, 10.0, 11.5, 14.0, 300.0])
        rows = np.full(cols.shape, centre[1])
        none = ax.classify(mask, cols, rows, margin_nm=0.0)
        assert list(none.labels) == [ax.LABEL_INTERIOR, ax.LABEL_INTERIOR,
                                     ax.LABEL_INTERIOR, ax.LABEL_MEMBRANE,
                                     ax.LABEL_OUTSIDE], none.labels
        wide = ax.classify(mask, cols, rows, margin_nm=150.0)
        assert list(wide.labels[:4]) == [ax.LABEL_INTERIOR, ax.LABEL_INTERIOR,
                                         ax.LABEL_MEMBRANE, ax.LABEL_MEMBRANE]
        assert wide.fraction_interior == 0.5, wide.fraction_interior
        return "a 150 nm margin moves the 56 nm-deep one to membrane"

    def ring_on_the_edge():
        rng = np.random.default_rng(5)
        angle = rng.uniform(0, 2 * np.pi, 5000)
        r = radius + rng.normal(0, 0.3, angle.size)
        cols = centre[0] + r * np.cos(angle)
        rows = centre[1] + r * np.sin(angle)
        result = ax.classify(mask, cols, rows, margin_nm=0.0)
        assert 0.35 < result.fraction_interior < 0.65, result.fraction_interior
        wide = ax.classify(mask, cols, rows, margin_nm=150.0)
        assert wide.fraction_interior < 0.05, wide.fraction_interior
        return (f"a ring on the edge: {result.fraction_interior:.0%} interior "
                f"without a margin, {wide.fraction_interior:.0%} with 150 nm")

    def summary():
        cols = centre[0] + np.array([2.0, 14.0])
        rows = np.full(cols.shape, centre[1])
        result = ax.classify(mask, cols, rows, 0.0)
        reg = ax.ImageRegistration(shift_px=(1.0, -2.0), source="manual")
        kwargs = dict(localizations="a.hdf5", tubulin="t.tif", reference="",
                      registration_file="", roi="none", pixel_size_nm=PIXEL_NM,
                      offset_px=(0.0, 0.0), registration=reg, mask=mask,
                      result=result)
        without = ax.summary_row(cluster_result=None, **kwargs)
        with_clusters = ax.summary_row(cluster_result=result, **kwargs)
        assert list(without) == list(with_clusters)
        assert without["n_clusters"] is None
        assert with_clusters["n_clusters_interior"] == 1
        assert without["shift_x_nm"] == 113.0 and without["shift_y_nm"] == -226.0
        assert without["n_interior"] == 1 and without["fraction_interior"] == 0.5
        return f"{len(without)} columns, the same with or without clusters"

    check("the margin", margin)
    check("a spectrin ring on a blurred edge", ring_on_the_edge)
    check("the summary row", summary)


# ============================================================ real data
def test_real_data() -> None:
    print("\n6. APRIL 2026, ROI 1  (widefield images and STORM data)")

    def april():
        if not all(os.path.exists(p) for p in (APRIL_FULL, APRIL_SPEC,
                                               APRIL_TUB, APRIL_AXON7)):
            return "skipped, data not present"
        from tools.mps_io import load_localizations

        spec = ax.load_widefield(APRIL_SPEC)
        tub = ax.load_widefield(APRIL_TUB)
        full = load_localizations(APRIL_FULL)
        px = full.pixel_size_nm
        off, notes = ax.camera_offset(spec, full.info, px)
        assert off == (0.0, 0.0) and not notes
        reg = ax.measure_shift(spec.image, full.x_nm / px + off[0],
                               full.y_nm / px + off[1])
        assert np.hypot(reg.shift_px[0] + 2.05, reg.shift_px[1] - 5.55) < 0.1, \
            reg.shift_px
        assert not reg.warnings, reg.warnings
        axon = load_localizations(APRIL_AXON7)
        toff, _ = ax.camera_offset(tub, axon.info, px)
        col = axon.x_nm / px + toff[0] + reg.shift_px[0]
        row = axon.y_nm / px + toff[1] + reg.shift_px[1]
        centre, radius, reach = ax.axon_centre(col, row)
        mask = ax.build_mask(tub.image, centre, radius, px, reach_px=reach)
        assert not mask.empty and not mask.warnings, mask.warnings
        assert 0.5 < mask.area_ratio < 2.0, mask.area_ratio
        result = ax.classify(mask, col, row, 250.0)
        assert result.count(ax.LABEL_OUTSIDE) == 0
        return (f"shift ({reg.shift_px[0]:+.2f}, {reg.shift_px[1]:+.2f}) px; "
                f"axon 7 mask {mask.area_ratio:.2f}x its ring, "
                f"{result.fraction_interior:.0%} interior with a 250 nm margin")

    check("registration and one axon", april)


def main() -> int:
    print("=" * 72)
    print("AXOPLASM MASK CHECKS")
    print("=" * 72)
    test_loading()
    test_placing()
    test_registration()
    test_mask()
    test_classification()
    test_real_data()
    print("\n" + "=" * 72)
    print(f"{PASSED} passed, {FAILED} failed")
    print("=" * 72)
    return 1 if FAILED else 0


if __name__ == "__main__":
    sys.exit(main())
