# -*- coding: utf-8 -*-
"""
Checks for the localization loader and the Picasso metadata reader.

Written as a standalone script, like the other ``validate_*.py`` in this
repository, because the venv has no pytest.

The cases that matter are the ones where a wrong answer is SILENT:

  * lpz is already in nanometres while lpx and lpy are in camera pixels.
    Scaling lpz by 113 would make every axial spread look 113x more
    precise than it is, and every ring perfectly resolved.
  * A Picasso >= 0.11 file may carry no YAML sidecar at all. The old
    loader refused it; the pixel size is in the embedded '/metadata'.
  * A file with neither must still be refused rather than defaulted.

Run:  python validate_io.py
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
import traceback

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from tools import mps_metadata  # noqa: E402
from tools.mps_io import (  # noqa: E402
    FORMAT_CUSTOM_CSV,
    FORMAT_PICASSO_HDF5,
    FORMAT_THUNDERSTORM_CSV,
    Localizations,
    duplicate_sources,
    find_localization_files,
    is_derived_output,
    load_localizations,
    read_pixel_size,
)

DATA_ROOT = os.environ.get(
    "MPS_VALIDATION_DATA",
    r"C:\Users\nicol\OneDrive\Doctorado\1°Reunión de avances de tesis\Abril",
)

PASSED = 0
FAILED = 0


def check(name: str, fn) -> None:
    global PASSED, FAILED
    try:
        detail = fn()
    except Exception as error:  # noqa: BLE001 - a harness, it reports everything
        FAILED += 1
        print(f"  FAIL  {name}")
        for line in traceback.format_exc().strip().splitlines()[-3:]:
            print(f"        {line}")
        return
    PASSED += 1
    print(f"  ok    {name}" + (f"   [{detail}]" if detail else ""))


# --------------------------------------------------------------- helpers
def write_hdf5(
    path: str,
    n: int = 50,
    *,
    with_z: bool = True,
    embedded_pixel_size: float | None = None,
    sidecar_pixel_size: float | None = None,
    locs_key: str = "locs",
) -> None:
    """A minimal Picasso-shaped file, with the metadata placed as asked."""
    import h5py as h5

    rng = np.random.default_rng(0)
    fields = [
        ("frame", np.uint32, rng.integers(0, 1000, n)),
        ("x", np.float32, rng.uniform(10, 20, n)),
        ("y", np.float32, rng.uniform(10, 20, n)),
        ("photons", np.float32, rng.uniform(500, 5000, n)),
        ("lpx", np.float32, np.full(n, 0.10)),
        ("lpy", np.float32, np.full(n, 0.10)),
    ]
    if with_z:
        fields += [
            ("z", np.float32, rng.uniform(-100, 100, n)),
            ("lpz", np.float32, np.full(n, 45.0)),
        ]
    dtype = np.dtype([(name, kind) for name, kind, _ in fields])
    table = np.zeros(n, dtype=dtype)
    for name, _kind, values in fields:
        table[name] = values

    with h5.File(path, "w") as handle:
        handle.create_dataset(locs_key, data=table)
        if embedded_pixel_size is not None:
            info = [
                {"Frames": 1000, "Width": 256, "Height": 256},
                {
                    "Generated by": "Picasso v0.11.1 Localize",
                    "Pixelsize": embedded_pixel_size,
                    "Box Size": 13,
                    "Fit method": "LQ, Gaussian",
                },
            ]
            handle.create_dataset("metadata", data=json.dumps(info))

    if sidecar_pixel_size is not None:
        with open(
            os.path.splitext(path)[0] + ".yaml", "w", encoding="utf-8"
        ) as handle:
            handle.write("Frames: 1000\nWidth: 256\nHeight: 256\n---\n")
            handle.write("Generated by: Picasso v0.9.10 Localize\n")
            handle.write(f"Pixelsize: {sidecar_pixel_size}\nBox Size: 9\n")


def find_real_axon() -> str | None:
    import glob

    for pattern in ("ROI 1/*.hdf5", "ROI 1/*/*.hdf5", "ROI 2/*.hdf5"):
        hits = [
            f
            for f in glob.glob(os.path.join(DATA_ROOT, pattern))
            if "axon" in os.path.basename(f).lower()
        ]
        if hits:
            return sorted(hits)[0]
    return None


# ================================================== 1. metadata reading
def test_metadata() -> None:
    print("\n1. METADATA CHAIN")

    def newest_wins():
        info = [{"Pixelsize": 133}, {"Pixelsize": 113}]
        assert mps_metadata.pixel_size_nm(info) == 113.0
        return "later step overrides earlier"

    def falsy_is_found():
        # Picasso's own get_from_metadata uses `if val := inf.get(key)`,
        # so it would skip a 0 and keep searching. This must not.
        info = [{"Box Size": 9}, {"Box Size": 0}]
        assert mps_metadata.get_value(info, "Box Size") == 0
        return "Box Size: 0 returned, not skipped"

    def explicit_null_skipped():
        # Picasso writes `lpz: null` in a Filter step to mean "not
        # applied". That must fall through to an older real value.
        info = [{"lpz": [0.0, 0.15]}, {"Generated by": "Filter", "lpz": None}]
        assert mps_metadata.get_value(info, "lpz") == [0.0, 0.15]
        return "null falls through"

    def missing_is_default():
        assert mps_metadata.get_value([{"a": 1}], "b", default=7) == 7
        assert mps_metadata.pixel_size_nm([]) is None
        return None

    def step_lookup():
        info = [
            {"Generated by": "Picasso v0.9.10 Localize", "Box Size": 9},
            {"Generated by": "Picasso v0.9.10 Filter", "lpx": [0, 0.15]},
        ]
        assert mps_metadata.step_containing(info, "Localize")["Box Size"] == 9
        assert mps_metadata.step_containing(info, "filter") is not None
        assert mps_metadata.step_containing(info, "Average") is None
        return "case-insensitive substring"

    def bulky_stripped():
        info = [{"Micro-Manager Metadata": {"a": 1}, "Pixelsize": 113}]
        out = mps_metadata.strip_bulky(info)
        assert out == [{"Pixelsize": 113}]
        return None

    check("newest step wins", newest_wins)
    check("a falsy value is returned, not skipped", falsy_is_found)
    check("an explicit null falls through", explicit_null_skipped)
    check("missing key gives the default", missing_is_default)
    check("step lookup by name", step_lookup)
    check("Micro-Manager block strippable", bulky_stripped)


# ============================================== 2. where the pixel size comes from
def test_pixel_size_sources() -> None:
    print("\n2. PIXEL SIZE PROVENANCE")
    tmp = tempfile.mkdtemp(prefix="mps_io_")

    def from_sidecar():
        path = os.path.join(tmp, "sidecar.hdf5")
        write_hdf5(path, sidecar_pixel_size=113.0)
        loc = load_localizations(path)
        assert loc.pixel_size_nm == 113.0
        assert loc.pixel_size_source == "yaml"
        return "yaml"

    def from_embedded():
        # The Picasso >= 0.11 case the old loader refused outright.
        path = os.path.join(tmp, "embedded.hdf5")
        write_hdf5(path, embedded_pixel_size=130.0)
        assert not os.path.exists(os.path.splitext(path)[0] + ".yaml")
        loc = load_localizations(path)
        assert loc.pixel_size_nm == 130.0
        assert loc.pixel_size_source == "hdf5"
        assert loc.box_size_px == 13
        return "no sidecar, /metadata used"

    def sidecar_preferred():
        path = os.path.join(tmp, "both.hdf5")
        write_hdf5(path, embedded_pixel_size=130.0, sidecar_pixel_size=113.0)
        loc = load_localizations(path)
        assert loc.pixel_size_nm == 113.0, loc.pixel_size_nm
        return "sidecar beats embedded, as in picasso.io.load_info"

    def override_wins():
        path = os.path.join(tmp, "override.hdf5")
        write_hdf5(path, sidecar_pixel_size=113.0)
        loc = load_localizations(path, pixel_size_nm=160.0)
        assert loc.pixel_size_nm == 160.0
        assert loc.pixel_size_source == "override"
        return None

    def refuses_when_unknown():
        path = os.path.join(tmp, "naked.hdf5")
        write_hdf5(path)
        try:
            load_localizations(path)
        except ValueError as error:
            assert "pixel size" in str(error).lower()
            return "refused, did not default to 133"
        raise AssertionError("loaded a file with no pixel size anywhere")

    def malformed_sidecar_still_scanned():
        path = os.path.join(tmp, "broken.hdf5")
        write_hdf5(path)
        with open(
            os.path.splitext(path)[0] + ".yaml", "w", encoding="utf-8"
        ) as handle:
            handle.write("Pixelsize: 113\n\tthis: [is not, valid yaml\n")
        loc = load_localizations(path)
        assert loc.pixel_size_nm == 113.0
        assert loc.pixel_size_source == "yaml_scan"
        return "fallback line scan"

    def read_pixel_size_helper():
        path = os.path.join(tmp, "helper.hdf5")
        write_hdf5(path, embedded_pixel_size=108.0)
        assert read_pixel_size(path) == 108.0
        return "works without a sidecar now"

    check("sidecar", from_sidecar)
    check("embedded /metadata, no sidecar", from_embedded)
    check("sidecar preferred over embedded", sidecar_preferred)
    check("explicit override wins", override_wins)
    check("refuses when nothing knows it", refuses_when_unknown)
    check("malformed sidecar falls back to a scan", malformed_sidecar_still_scanned)
    check("read_pixel_size()", read_pixel_size_helper)


# ============================================================ 3. units
def test_units() -> None:
    print("\n3. UNITS  (the trap this phase exists to close)")
    tmp = tempfile.mkdtemp(prefix="mps_io_u_")
    path = os.path.join(tmp, "units.hdf5")
    write_hdf5(path, sidecar_pixel_size=100.0)
    loc = load_localizations(path)

    def xy_scaled():
        assert np.allclose(loc.x_nm, np.asarray(loc.columns["x"], float) * 100.0)
        return "x * pixel size"

    def lpxy_scaled():
        # 0.10 camera pixels at 100 nm/px = 10 nm.
        assert np.allclose(loc.lpx_nm, 10.0)
        assert np.allclose(loc.lpy_nm, 10.0)
        return "0.10 px -> 10.0 nm"

    def lpz_not_scaled():
        # The whole point: lpz is stored in nm already.
        assert np.allclose(loc.lpz_nm, 45.0), np.median(loc.lpz_nm)
        assert not np.allclose(loc.lpz_nm, 4500.0)
        return "45 nm stays 45 nm, not 4500"

    def z_not_scaled():
        assert np.allclose(loc.z_nm, np.asarray(loc.columns["z"], float))
        return None

    def lateral_mean():
        assert np.allclose(loc.lp_lateral_nm, 10.0)
        return None

    def native_untouched():
        assert np.allclose(loc.columns["lpx"], 0.10)
        return "columns[] keeps native units"

    def failed_fits_marked():
        # A median of 0.10 px, one axis collapsed on four localizations.
        lpx = np.full(200, 0.10)
        lpy = np.full(200, 0.10)
        lpx[0], lpy[1], lpx[2], lpy[3] = 0.0, np.inf, 1e-8, 0.005
        lpx[4] = 0.03                      # bright but genuine: 0.3x
        bad = Localizations(
            x_nm=np.zeros(200), y_nm=np.zeros(200), z_nm=np.zeros(200),
            path="synthetic", fileformat=FORMAT_PICASSO_HDF5,
            pixel_size_nm=100.0, pixel_size_source="test",
            columns={"lpx": lpx, "lpy": lpy},
        )
        lp = bad.lp_lateral_nm
        assert np.all(np.isnan(lp[:4])), lp[:5]
        assert np.all(np.isfinite(lp[4:])), lp[:6]
        assert abs(lp[4] - 6.5) < 1e-9, lp[4]
        # The same tiny precision on a BRIGHT localization is genuine.
        photons = np.linspace(500.0, 1100.0, 200)
        photons[2], photons[3] = 90_000.0, 100.0
        bright = Localizations(
            x_nm=np.zeros(200), y_nm=np.zeros(200), z_nm=np.zeros(200),
            path="synthetic", fileformat=FORMAT_PICASSO_HDF5,
            pixel_size_nm=100.0, pixel_size_source="test",
            columns={"lpx": lpx, "lpy": lpy, "photons": photons},
        )
        lp = bright.lp_lateral_nm
        assert np.isfinite(lp[2]) and np.isnan(lp[3]), lp[:4]
        # And in a file of merged events (Picasso link), on any of them.
        linked = Localizations(
            x_nm=np.zeros(200), y_nm=np.zeros(200), z_nm=np.zeros(200),
            path="synthetic", fileformat=FORMAT_PICASSO_HDF5,
            pixel_size_nm=100.0, pixel_size_source="test",
            columns={"lpx": lpx, "lpy": lpy, "n": np.ones(200)},
        )
        lp = linked.lp_lateral_nm
        assert np.all(np.isfinite(lp[2:])) and np.all(np.isnan(lp[:2])), lp[:5]
        return ("zero, infinite and collapsed fits NaN; a 0.3x one, a bright "
                "one and merged events kept")

    check("x and y scaled to nm", xy_scaled)
    check("lpx and lpy scaled to nm", lpxy_scaled)
    check("lpz NOT scaled", lpz_not_scaled)
    check("z NOT scaled", z_not_scaled)
    check("lp_lateral_nm", lateral_mean)
    check("native columns untouched", native_untouched)
    check("failed fits marked in lp_lateral_nm", failed_fits_marked)


# ================================================= 4. shape and failure modes
def test_shapes_and_errors() -> None:
    print("\n4. SHAPES AND FAILURE MODES")
    tmp = tempfile.mkdtemp(prefix="mps_io_s_")

    def two_d_file():
        path = os.path.join(tmp, "flat.hdf5")
        write_hdf5(path, with_z=False, sidecar_pixel_size=113.0)
        loc = load_localizations(path)
        assert loc.z_nm.shape == loc.x_nm.shape
        assert np.all(loc.z_nm == 0.0)
        assert loc.is_3d is False
        assert loc.lpz_nm is None
        return "z zeros, is_3d False, lpz_nm None"

    def three_d_file():
        path = os.path.join(tmp, "vol.hdf5")
        write_hdf5(path, sidecar_pixel_size=113.0)
        assert load_localizations(path).is_3d is True
        return None

    def no_locs_dataset():
        path = os.path.join(tmp, "groups.hdf5")
        write_hdf5(path, sidecar_pixel_size=113.0, locs_key="groups")
        try:
            load_localizations(path)
        except ValueError as error:
            assert "locs" in str(error)
            return "clear error, not a KeyError"
        raise AssertionError("accepted a file with no /locs")

    def missing_column_is_none():
        path = os.path.join(tmp, "vol2.hdf5")
        write_hdf5(path, sidecar_pixel_size=113.0)
        loc = load_localizations(path)
        assert loc.column("net_gradient") is None
        assert loc.has("net_gradient") is False
        assert loc.has("frame") is True
        return None

    def bad_extension():
        try:
            load_localizations(os.path.join(tmp, "x.txt"))
        except ValueError as error:
            assert "extension" in str(error).lower()
            return None
        raise AssertionError("accepted an unknown extension")

    check("2D file (no z column)", two_d_file)
    check("3D file", three_d_file)
    check("HDF5 without /locs", no_locs_dataset)
    check("absent column reads as None", missing_column_is_none)
    check("unknown extension", bad_extension)


# ======================================================== 5. CSV paths
def test_csv() -> None:
    print("\n5. CSV")
    tmp = tempfile.mkdtemp(prefix="mps_io_c_")

    def thunderstorm():
        path = os.path.join(tmp, "ts.csv")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(
                "frame,x [nm],y [nm],z [nm],intensity [photon],"
                "uncertainty_xy [nm]\n"
            )
            # ThunderSTORM numbers frames from 1.
            for i in range(10):
                handle.write(
                    f"{i + 1},{100 + i},{200 + i},{i * 10},900,12.5\n")
        loc = load_localizations(path)
        assert loc.pixel_size_source == "not_applicable"
        assert loc.n == 10
        # Already nm, and no pixel size exists to wrongly apply.
        assert np.allclose(loc.lpx_nm, 12.5)
        assert np.allclose(loc.photons, 900.0)
        # Counted from 0 like Picasso's, while columns[] keeps the file's.
        assert loc.frame is not None and loc.frame[0] == 0, loc.frame
        assert int(np.asarray(loc.columns["frame"])[0]) == 1
        assert loc.subset(np.arange(5, 10)).frame[0] == 5
        # Picasso's own "Export for ThunderSTORM" keeps 0-based frames and
        # writes a background-noise column of zeros.
        exported = os.path.join(tmp, "from_picasso.csv")
        with open(exported, "w", encoding="utf-8") as handle:
            handle.write("id,frame,x [nm],y [nm],z [nm],bkgstd [photon]\n")
            for i in range(10):
                handle.write(f"{i},{i + 12},{100 + i},{200 + i},0,0\n")
        picasso = load_localizations(exported)
        assert picasso.frame is not None and picasso.frame[0] == 12
        return ("aliases resolved, no scaling invented, ThunderSTORM frames "
                "from 0, Picasso's export left alone")

    def custom_three_columns():
        path = os.path.join(tmp, "bare.csv")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("a,b,c\n1,2,3\n4,5,6\n")
        loc = load_localizations(path, fileformat=FORMAT_CUSTOM_CSV)
        assert loc.n == 2 and loc.z_nm[1] == 6
        return None

    def bare_csv_refused_by_default():
        path = os.path.join(tmp, "bare2.csv")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("a,b,c\n1,2,3\n")
        try:
            load_localizations(path, fileformat=FORMAT_THUNDERSTORM_CSV)
        except ValueError:
            return "three numeric columns are not assumed to be x,y,z"
        raise AssertionError("guessed coordinates from an arbitrary CSV")

    check("ThunderSTORM csv", thunderstorm)
    check("custom csv, asked for by name", custom_three_columns)
    check("bare csv refused unless asked", bare_csv_refused_by_default)


# ================================================== 6. the real dataset
def test_real_data() -> None:
    print("\n6. REAL DATA")
    path = find_real_axon()
    if path is None:
        print(f"  skip  no axon files under {DATA_ROOT!r}")
        return
    loc = load_localizations(path)

    def columns_present():
        expected = {
            "frame", "x", "y", "photons", "sx", "sy", "bg",
            "lpx", "lpy", "ellipticity", "net_gradient", "z",
            "d_zcalib", "lpz",
        }
        missing = expected - set(loc.columns)
        assert not missing, f"missing {sorted(missing)}"
        return f"{len(loc.columns)} columns, {loc.n:,} locs"

    def metadata_chain():
        assert loc.metadata_source == "yaml"
        assert loc.n_frames == 60000
        assert loc.box_size_px == 9
        assert loc.fit_method and "Gaussian" in loc.fit_method
        assert loc.z_calibration is not None
        assert len(loc.processing_steps) >= 4
        return f"{len(loc.processing_steps)} steps, {loc.n_frames} frames"

    def precisions_sane():
        lpx, lpz = np.median(loc.lpx_nm), np.median(loc.lpz_nm)
        assert 5.0 < lpx < 20.0, f"lpx {lpx}"
        assert 30.0 < lpz < 80.0, f"lpz {lpz}"
        assert lpz > 3 * lpx, "axial precision should be far worse than lateral"
        return f"lpx {lpx:.1f} nm, lpz {lpz:.1f} nm"

    def coordinates_unchanged():
        # The contract every existing caller depends on.
        import h5py as h5

        with h5.File(path, "r") as handle:
            table = handle["locs"]
            x = np.asarray(table["x"], float) * 113.0
            z = np.asarray(table["z"], float)
        assert np.allclose(loc.x_nm, x)
        assert np.allclose(loc.z_nm, z)
        return "identical to the old three-column path"

    def frames_span_movie():
        frame = loc.frame
        assert frame is not None
        assert frame.min() >= 0 and frame.max() < loc.n_frames + 1
        return f"{frame.min()}..{frame.max()}"

    check("every expected column read", columns_present)
    check("metadata chain parsed", metadata_chain)
    check("precisions in range", precisions_sane)
    check("x/y/z identical to before", coordinates_unchanged)
    check("frames within the acquisition", frames_span_movie)


# ==================================================== 7. existing callers
def test_backwards_compatibility() -> None:
    print("\n7. EXISTING CALLERS")

    def dataclass_positional():
        # batch_rings.py and mps_batch.py construct and read these.
        loc = Localizations(
            x_nm=np.zeros(3),
            y_nm=np.zeros(3),
            z_nm=np.zeros(3),
            path="p",
            fileformat=0,
            pixel_size_nm=113.0,
            pixel_size_source="yaml",
        )
        assert loc.n == 3
        assert loc.columns == {} and loc.info == []
        return "new fields all default"

    def batch_runner_imports():
        import importlib

        for name in ("batch_rings", "tools.mps_batch"):
            importlib.import_module(name)
        return "batch_rings, mps_batch"

    check("Localizations without the new fields", dataclass_positional)
    check("downstream modules still import", batch_runner_imports)


# =========================================== 8. derived-output exclusion
def test_derived_outputs() -> None:
    print("\n8. DERIVED OUTPUTS  (MPS Explorer's own files, read back as input)")

    def known_suffixes():
        for name in (
            "axon7_cluster_centers.csv",
            "axon7_all_clusters.csv",
            "axon7neighbor_distances.csv",
            "pick_01_filtered_clusters_thunderstorm_ep15.csv",
        ):
            assert is_derived_output(name), name
        return "4 suffixes"

    def roi_export_excluded():
        # save_roi writes "{stem}_ch{channel}_roi.csv". This was NOT
        # excluded, so a batch read every axon twice.
        for name in (
            "..._picked_axon7_ch1_roi.csv",
            "..._picked_Axon1_roi2_ch1_roi.csv",
            "..._picked_axon3_ch2_roi.csv",
            # Renamed by hand afterwards; the marker still identifies it.
            # An anchored \b would let exactly this one through, because
            # "_" is a word character.
            "..._picked_Axon1_ch1_roi_filterby-123to57.csv",
        ):
            assert is_derived_output(name), name
        return "_ch{N}_roi excluded, even when renamed"

    def real_files_kept():
        # "_roi2" is part of real filenames in this dataset; a substring
        # rule on "_roi" would have thrown the actual data away.
        for name in (
            "..._picked_axon2_roi2.hdf5",
            "..._picked_Axon1_roi2.hdf5",
            "..._render_RCC1000_picked_axon9.hdf5",
        ):
            assert not is_derived_output(name), name
        return "_roi2 files kept"

    def collision_detected():
        found = duplicate_sources(
            [
                "/d/x_picked_axon7.hdf5",
                "/d/x_picked_axon7_ch1_roi.csv",
                "/d/x_picked_axon8.hdf5",
            ]
        )
        assert len(found) == 1, found
        assert len(next(iter(found.values()))) == 2
        return "hdf5 + its ROI export grouped"

    def no_false_collision():
        assert duplicate_sources(
            ["/d/x_picked_axon7.hdf5", "/d/x_picked_axon8.hdf5"]
        ) == {}
        # Different ROIs of the same movie are different acquisitions.
        assert duplicate_sources(
            ["/d/x_picked_axon2_roi2.hdf5", "/d/x_picked_axon2.hdf5"]
        ) == {}
        return "distinct axons not grouped"

    def picasso_outputs():
        for name in (
            "x_picked_axon7_clusters.hdf5",
            "x_picked_axon7_cluster_centers.hdf5",
            "x_picked_axon7_clusters_molmap.hdf5",
            "x_picked_axon7_aim_clusters.hdf5",
            "x_picked_axon7_link.hdf5",
        ):
            assert is_derived_output(name), name
        # A drift-corrected copy may be the file to analyse: kept, but
        # reported as the same acquisition as its original.
        assert not is_derived_output("x_picked_axon7_aim.hdf5")
        found = duplicate_sources(
            ["/d/x_picked_axon7.hdf5", "/d/x_picked_axon7_aim.hdf5"])
        assert len(found) == 1, found
        assert duplicate_sources(["/d/x_aimed_axon7.hdf5",
                                  "/d/x_axon7.hdf5"]) == {}
        # Whole tokens only: the user's own Picasso-linked files are input.
        for name in ("x_undrift_filter__linked.hdf5",
                     "x__linked_picked_axon2.hdf5",
                     "x_axon2_clustersA.hdf5", "x_linkage.hdf5"):
            assert not is_derived_output(name), name
        assert duplicate_sources(["/d/x__linked_picked_axon2.hdf5",
                                  "/d/x_picked_axon2.hdf5"]) == {}
        return "clusters/molmap/link skipped; _aim reported as a duplicate"

    def real_folder_is_clean_now():
        root = os.path.join(DATA_ROOT, "ROI 2")
        if not os.path.isdir(root):
            return "skipped, dataset not present"
        files, skipped = find_localization_files(root)
        collisions = duplicate_sources(files)
        assert not collisions, collisions
        return f"{len(files)} kept, {len(skipped)} skipped, 0 collisions"

    check("known derived suffixes", known_suffixes)
    check("the ROI export that was slipping through", roi_export_excluded)
    check("real _roi2 filenames NOT excluded", real_files_kept)
    check("duplicate acquisition detected", collision_detected)
    check("distinct acquisitions not flagged", no_false_collision)
    check("files written by the Picasso tools", picasso_outputs)
    check("real ROI 2 folder", real_folder_is_clean_now)


def main() -> int:
    print("=" * 72)
    print("LOADER AND METADATA CHECKS")
    print("=" * 72)
    test_metadata()
    test_pixel_size_sources()
    test_units()
    test_shapes_and_errors()
    test_csv()
    test_real_data()
    test_backwards_compatibility()
    test_derived_outputs()
    print("\n" + "=" * 72)
    print(f"{PASSED} passed, {FAILED} failed")
    print("=" * 72)
    return 1 if FAILED else 0


if __name__ == "__main__":
    sys.exit(main())
