# -*- coding: utf-8 -*-
"""
Reading the Picasso metadata chain that travels with a localization file.

Picasso records its processing history as a LIST of documents: one per
step (Localize, Filter, Render, Pick, ...), each a mapping. Until v0.11
that list lived only in a ``.yaml`` sidecar; since v0.11 it is also
embedded in the HDF5 file itself as a JSON string under ``/metadata``,
and the sidecar can be switched off entirely (user setting "Save
metadata in .yaml"). Both have to work:

  * the data in this project was written by Picasso v0.9.10 -- sidecar
    only, no ``/metadata``;
  * a file written by a current Picasso may carry ``/metadata`` only.

Order of preference follows ``picasso.io.load_info``: sidecar first
(hand-inspectable, hand-editable), embedded second.

Why not just grep for ``Pixelsize:``
------------------------------------
That is what this project did before, and it works, but it throws away
the rest: the number of frames, the fitting box size, the astigmatism
calibration, which Filter cuts were already applied, the pick shape.
None of those can be recovered from the localization table, and each one
decides whether a measurement downstream is trustworthy. The
line-scanning fallback is kept for a sidecar too malformed to parse, but
it is the fallback now, not the method.

@author: Nicolas (ngomez) + Claude
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

# Metadata document keys used often enough to be worth naming once.
KEY_PIXELSIZE = "Pixelsize"
KEY_FRAMES = "Frames"
KEY_BOX_SIZE = "Box Size"
KEY_FIT_METHOD = "Fit method"
KEY_Z_CALIBRATION = "Z Calibration"
KEY_GENERATED_BY = "Generated by"

MetadataInfo = List[Dict[str, Any]]


def metadata_path(data_path: str) -> str:
    """Path of the YAML sidecar Picasso writes next to ``data_path``."""
    return os.path.splitext(data_path)[0] + ".yaml"


def _load_yaml_sidecar(path: str) -> Optional[MetadataInfo]:
    """
    Every document of the YAML sidecar, or None when there is no sidecar
    or it cannot be parsed at all.

    Returns None rather than raising: a missing or broken sidecar is a
    normal condition, resolved by the caller trying the embedded copy.
    """
    sidecar = metadata_path(path)
    if not os.path.exists(sidecar):
        return None
    try:
        # PyYAML ships no type stubs and types-PyYAML is not a dependency
        # of this project; the import is narrowed rather than adding one.
        import yaml  # type: ignore[import-untyped]

        with open(sidecar, "r", encoding="utf-8", errors="ignore") as handle:
            docs = list(yaml.safe_load_all(handle))
    except Exception:
        return None
    info = [d for d in docs if isinstance(d, dict)]
    return info or None


def _load_embedded(path: str) -> Optional[MetadataInfo]:
    """
    The ``/metadata`` dataset of a Picasso >= 0.11 HDF5 file, or None.

    Picasso stores it as a JSON string; h5py hands it back as bytes or
    str depending on how it was written, so both are accepted.
    """
    if os.path.splitext(path)[1].lower() not in (".hdf5", ".h5"):
        return None
    try:
        import h5py as h5

        with h5.File(path, "r") as handle:
            if "metadata" not in handle:
                return None
            raw = handle["metadata"][()]
    except Exception:
        return None
    if isinstance(raw, bytes):
        raw = raw.decode("utf-8", errors="ignore")
    try:
        parsed = json.loads(raw)
    except (ValueError, TypeError):
        return None
    if isinstance(parsed, dict):
        parsed = [parsed]
    if not isinstance(parsed, list):
        return None
    info = [d for d in parsed if isinstance(d, dict)]
    return info or None


def _scan_for_pixel_size(path: str) -> Optional[float]:
    """
    Last-resort ``Pixelsize:`` scan of the sidecar, line by line.

    Kept for a sidecar whose other keys are malformed badly enough that
    the YAML parser gives up: the pixel size is the one value whose
    absence silently corrupts every lateral distance downstream, so it
    earns one more attempt on its own.
    """
    sidecar = metadata_path(path)
    if not os.path.exists(sidecar):
        return None
    try:
        with open(sidecar, "r", encoding="utf-8", errors="ignore") as handle:
            for line in handle:
                if line.strip().startswith(KEY_PIXELSIZE + ":"):
                    return float(line.split(":", 1)[1].strip())
    except (OSError, ValueError):
        return None
    return None


def load_metadata(path: str) -> Tuple[MetadataInfo, str]:
    """
    The Picasso metadata chain for ``path`` and where it came from.

    Returns
    -------
    (info, source), with ``source`` one of "yaml", "hdf5", "yaml_scan"
    or "none". ``info`` is empty when ``source`` is "none"; for
    "yaml_scan" it holds a single synthesised document carrying only the
    pixel size, so a caller that only needs to convert coordinates can
    proceed while a caller that inspects the processing history sees
    plainly that there is none.
    """
    info = _load_yaml_sidecar(path)
    if info is not None:
        return info, "yaml"
    info = _load_embedded(path)
    if info is not None:
        return info, "hdf5"
    scanned = _scan_for_pixel_size(path)
    if scanned is not None:
        return [{KEY_PIXELSIZE: scanned}], "yaml_scan"
    return [], "none"


def get_value(
    info: Sequence[Dict[str, Any]], key: str, default: Any = None
) -> Any:
    """
    Look a key up in the metadata chain, newest step first.

    Newest-first because a later step overrides an earlier one; Picasso's
    own ``lib.get_from_metadata`` does the same. It differs in one
    detail, on purpose -- Picasso tests the VALUE for truthiness
    (``if val := inf.get(key)``), so a legitimately falsy entry such as
    ``Box Size: 0`` is skipped and the search runs on into older
    documents. Membership is tested here instead, so a present-but-falsy
    value is returned as found. ``None`` is still skipped, because
    Picasso writes explicit nulls for "not applied" (every unused cut in
    a Filter step is ``null``).
    """
    for document in reversed(list(info)):
        if isinstance(document, dict) and key in document:
            value = document[key]
            if value is not None:
                return value
    return default


def pixel_size_nm(info: Sequence[Dict[str, Any]]) -> Optional[float]:
    """Camera pixel size in nm from the metadata, or None."""
    value = get_value(info, KEY_PIXELSIZE)
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def steps(info: Sequence[Dict[str, Any]]) -> List[str]:
    """The ``Generated by`` line of each step, oldest first."""
    out: List[str] = []
    for document in info:
        if isinstance(document, dict) and KEY_GENERATED_BY in document:
            out.append(str(document[KEY_GENERATED_BY]))
    return out


def step_containing(
    info: Sequence[Dict[str, Any]], name: str
) -> Optional[Dict[str, Any]]:
    """
    The newest step whose ``Generated by`` contains ``name``.

    ``step_containing(info, "Localize")`` finds the fitting parameters,
    ``"Filter"`` the cuts already applied, ``"Pick"`` the pick geometry.
    """
    needle = name.lower()
    for document in reversed(list(info)):
        if not isinstance(document, dict):
            continue
        generated = document.get(KEY_GENERATED_BY)
        if generated is not None and needle in str(generated).lower():
            return document
    return None


def strip_bulky(info: Sequence[Dict[str, Any]]) -> MetadataInfo:
    """
    The metadata without the Micro-Manager property dump.

    That block is several hundred camera settings copied verbatim from
    the acquisition. It is preserved faithfully in the file, but makes
    the metadata unreadable when echoed into a log or a report.
    """
    out: MetadataInfo = []
    for document in info:
        if not isinstance(document, dict):
            continue
        out.append(
            {
                k: v
                for k, v in document.items()
                if not str(k).startswith("Micro-Manager")
            }
        )
    return out
