# -*- coding: utf-8 -*-
"""
A synthetic Exchange-PAINT pair: one axon cross-section imaged in two rounds.

Round 1 holds betaII-spectrin, round 2 the partner protein. Both are rings
of clusters around the same axon, stacked along z with the MPS period; the
partner's rings sit ``phase`` of a period away from spectrin's. Both rounds
also hold markers localized in nearly every frame, far from the axon, and
round 2 is displaced by a known shift -- plus a known per-marker error --
as a sample that moved between rounds would be.

Used by the validation scripts to check the two-channel path end to end
against a known answer; written as Picasso HDF5 files with a YAML sidecar
so it goes through the same loader as real data.

@author: Nicolas (ngomez) + Claude
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

PIXEL_NM = 130.0
N_FRAMES = 3000


@dataclass
class SyntheticPair:
    path_a: str
    path_b: str
    centre_nm: Tuple[float, float]
    ring_radius_nm: float
    period_nm: float
    phase: float
    # Added to round 2 to bring it onto round 1.
    shift_nm: Tuple[float, float, float]
    marker_error_nm: Tuple[float, float]


def _rings(rng: np.random.Generator, centre: Tuple[float, float],
           radius: float, period: float, z_offset: float,
           angle_offset: float) -> Tuple[np.ndarray, ...]:
    xs, ys, zs = [], [], []
    # Three rings, as a section holds: the axial fit looks for two or
    # three. The middle one, cut through its centre, is the densest.
    for k in (-1, 0, 1):
        angles = angle_offset + np.linspace(0, 2 * np.pi, 16, endpoint=False)
        angles += rng.normal(0, 0.05, angles.size)
        for angle in angles:
            n = 60 if k == 0 else 30
            xs.append(centre[0] + radius * np.cos(angle) + rng.normal(0, 8, n))
            ys.append(centre[1] + radius * np.sin(angle) + rng.normal(0, 8, n))
            zs.append(k * period + z_offset + rng.normal(0, 25, n))
    x, y, z = (np.concatenate(v) for v in (xs, ys, zs))
    frame = rng.integers(0, N_FRAMES, x.size)
    return frame, x, y, z


def _markers(rng: np.random.Generator, positions: np.ndarray,
             presence: float = 0.95) -> Tuple[np.ndarray, ...]:
    frames, xs, ys, zs = [], [], [], []
    for mx, my, mz in positions:
        on = np.nonzero(rng.random(N_FRAMES) < presence)[0]
        frames.append(on)
        xs.append(mx + rng.normal(0, 2, on.size))
        ys.append(my + rng.normal(0, 2, on.size))
        zs.append(mz + rng.normal(0, 5, on.size))
    return (np.concatenate(frames), np.concatenate(xs),
            np.concatenate(ys), np.concatenate(zs))


def _write(path: str, frame: np.ndarray, x: np.ndarray, y: np.ndarray,
           z: np.ndarray, rng: np.random.Generator) -> None:
    import h5py

    order = np.argsort(frame, kind="stable")
    n = frame.size
    rows = np.zeros(n, dtype=[
        ("frame", "u4"), ("x", "f4"), ("y", "f4"), ("z", "f4"),
        ("photons", "f4"), ("sx", "f4"), ("sy", "f4"), ("bg", "f4"),
        ("lpx", "f4"), ("lpy", "f4"), ("lpz", "f4")])
    rows["frame"] = frame[order]
    rows["x"] = x[order] / PIXEL_NM
    rows["y"] = y[order] / PIXEL_NM
    rows["z"] = z[order]
    rows["photons"] = rng.normal(900, 150, n).clip(200)
    rows["sx"] = rows["sy"] = 1.1
    rows["bg"] = 90
    rows["lpx"] = rows["lpy"] = 8.0 / PIXEL_NM
    rows["lpz"] = 25.0
    with h5py.File(path, "w") as handle:
        handle.create_dataset("locs", data=rows)
    with open(os.path.splitext(path)[0] + ".yaml", "w",
              encoding="utf-8") as handle:
        handle.write(f"Frames: {N_FRAMES}\nWidth: 256\nHeight: 256\n---\n")
        handle.write("Generated by: synthetic Exchange-PAINT pair\n")
        handle.write(f"Pixelsize: {PIXEL_NM:g}\n")


def write_pair(
    folder: str,
    *,
    seed: int = 0,
    phase: float = 0.5,
    shift_nm: Tuple[float, float, float] = (-1200.0, 900.0, -30.0),
    marker_error_nm: Tuple[float, float] = (4.0, 8.0),
    n_markers: int = 8,
    name: Optional[str] = None,
) -> SyntheticPair:
    """Write round 1 and round 2 into ``folder`` and describe them."""
    rng = np.random.default_rng(seed)
    centre = (16000.0, 16000.0)
    radius, period = 400.0, 190.0
    fa, xa, ya, za = _rings(rng, centre, radius, period, 0.0, 0.0)
    fb, xb, yb, zb = _rings(rng, centre, radius, period, phase * period,
                            np.pi / 16)
    markers = np.column_stack([
        rng.uniform(3000, 29000, n_markers),
        rng.uniform(3000, 7000, n_markers),
        rng.uniform(-30, 30, n_markers),
    ])
    shift = np.asarray(shift_nm, dtype=float)
    noise = np.column_stack([
        rng.normal(0, marker_error_nm[0], n_markers),
        rng.normal(0, marker_error_nm[0], n_markers),
        rng.normal(0, marker_error_nm[1], n_markers),
    ])
    ma = _markers(rng, markers)
    mb = _markers(rng, markers - shift + noise)
    # Round 2 as recorded: everything displaced by -shift.
    xb, yb, zb = xb - shift[0], yb - shift[1], zb - shift[2]

    stem = name or f"pair{seed}"
    path_a = os.path.join(folder, f"{stem}_round1_spectrin.hdf5")
    path_b = os.path.join(folder, f"{stem}_round2_adducin.hdf5")
    _write(path_a, np.concatenate([fa, ma[0]]), np.concatenate([xa, ma[1]]),
           np.concatenate([ya, ma[2]]), np.concatenate([za, ma[3]]), rng)
    _write(path_b, np.concatenate([fb, mb[0]]), np.concatenate([xb, mb[1]]),
           np.concatenate([yb, mb[2]]), np.concatenate([zb, mb[3]]), rng)
    return SyntheticPair(
        path_a=path_a, path_b=path_b, centre_nm=centre,
        ring_radius_nm=radius, period_nm=period, phase=phase,
        shift_nm=(float(shift[0]), float(shift[1]), float(shift[2])),
        marker_error_nm=marker_error_nm,
    )
