# -*- coding: utf-8 -*-
"""
A synthetic Exchange-PAINT pair: one axon cross-section imaged in two rounds.

Round 1 holds betaII-spectrin, round 2 the partner protein. Both are rings
of clusters around the same axon, stacked along z with the MPS period; the
partner's rings sit ``phase`` of a period away from spectrin's. Both rounds
also hold markers localized in nearly every frame, far from the axon, and
round 2 is displaced by a known shift -- plus a known per-marker error --
as a sample that moved between rounds would be.

Used by the validation scripts to check the two-channel path end to end
against a known answer; written as Picasso HDF5 files with a YAML sidecar
so it goes through the same loader as real data.

@author: Nicolas (ngomez) + Claude
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

PIXEL_NM = 130.0
N_FRAMES = 3000


@dataclass
class SyntheticPair:
    path_a: str
    path_b: str
    centre_nm: Tuple[float, float]
    ring_radius_nm: float
    period_nm: float
    phase: float
    # Added to round 2 to bring it onto round 1.
    shift_nm: Tuple[float, float, float]
    marker_error_nm: Tuple[float, float]


def _rings(rng: np.random.Generator, centre: Tuple[float, float],
           radius: float, period: float, z_offset: float,
           angle_offset: float) -> Tuple[np.ndarray, ...]:
    xs, ys, zs = [], [], []
    # Three rings, as a section holds: the axial fit looks for two or
    # three. The middle one, cut through its centre, is the densest.
    for k in (-1, 0, 1):
        angles = angle_offset + np.linspace(0, 2 * np.pi, 16, endpoint=False)
        angles += rng.normal(0, 0.05, angles.size)
        for angle in angles:
            n = 60 if k == 0 else 30
            xs.append(centre[0] + radius * np.cos(angle) + rng.normal(0, 8, n))
            ys.append(centre[1] + radius * np.sin(angle) + rng.normal(0, 8, n))
            zs.append(k * period + z_offset + rng.normal(0, 25, n))
    x, y, z = (np.concatenate(v) for v in (xs, ys, zs))
    frame = rng.integers(0, N_FRAMES, x.size)
    return frame, x, y, z


def _markers(rng: np.random.Generator, positions: np.ndarray,
             presence: float = 0.95) -> Tuple[np.ndarray, ...]:
    frames, xs, ys, zs = [], [], [], []
    for mx, my, mz in positions:
        on = np.nonzero(rng.random(N_FRAMES) < presence)[0]
        frames.append(on)
        xs.append(mx + rng.normal(0, 2, on.size))
        ys.append(my + rng.normal(0, 2, on.size))
        zs.append(mz + rng.normal(0, 5, on.size))
    return (np.concatenate(frames), np.concatenate(xs),
            np.concatenate(ys), np.concatenate(zs))


def _write(path: str, frame: np.ndarray, x: np.ndarray, y: np.ndarray,
           z: np.ndarray, rng: np.random.Generator) -> None:
    import h5py

    order = np.argsort(frame, kind="stable")
    n = frame.size
    rows = np.zeros(n, dtype=[
        ("frame", "u4"), ("x", "f4"), ("y", "f4"), ("z", "f4"),
        ("photons", "f4"), ("sx", "f4"), ("sy", "f4"), ("bg", "f4"),
        ("lpx", "f4"), ("lpy", "f4"), ("lpz", "f4")])
    rows["frame"] = frame[order]
    rows["x"] = x[order] / PIXEL_NM
    rows["y"] = y[order] / PIXEL_NM
    rows["z"] = z[order]
    rows["photons"] = rng.normal(900, 150, n).clip(200)
    rows["sx"] = rows["sy"] = 1.1
    rows["bg"] = 90
    rows["lpx"] = rows["lpy"] = 8.0 / PIXEL_NM
    rows["lpz"] = 25.0
    with h5py.File(path, "w") as handle:
        handle.create_dataset("locs", data=rows)
    with open(os.path.splitext(path)[0] + ".yaml", "w",
              encoding="utf-8") as handle:
        handle.write(f"Frames: {N_FRAMES}\nWidth: 256\nHeight: 256\n---\n")
        handle.write("Generated by: synthetic Exchange-PAINT pair\n")
        handle.write(f"Pixelsize: {PIXEL_NM:g}\n")


def write_pair(
    folder: str,
    *,
    seed: int = 0,
    phase: float = 0.5,
    shift_nm: Tuple[float, float, float] = (-1200.0, 900.0, -30.0),
    marker_error_nm: Tuple[float, float] = (4.0, 8.0),
    n_markers: int = 8,
    name: Optional[str] = None,
) -> SyntheticPair:
    """Write round 1 and round 2 into ``folder`` and describe them."""
    rng = np.random.default_rng(seed)
    centre = (16000.0, 16000.0)
    radius, period = 400.0, 190.0
    fa, xa, ya, za = _rings(rng, centre, radius, period, 0.0, 0.0)
    fb, xb, yb, zb = _rings(rng, centre, radius, period, phase * period,
                            np.pi / 16)
    markers = np.column_stack([
        rng.uniform(3000, 29000, n_markers),
        rng.uniform(3000, 7000, n_markers),
        rng.uniform(-30, 30, n_markers),
    ])
    shift = np.asarray(shift_nm, dtype=float)
    noise = np.column_stack([
        rng.normal(0, marker_error_nm[0], n_markers),
        rng.normal(0, marker_error_nm[0], n_markers),
        rng.normal(0, marker_error_nm[1], n_markers),
    ])
    ma = _markers(rng, markers)
    mb = _markers(rng, markers - shift + noise)
    # Round 2 as recorded: everything displaced by -shift.
    xb, yb, zb = xb - shift[0], yb - shift[1], zb - shift[2]

    stem = name or f"pair{seed}"
    path_a = os.path.join(folder, f"{stem}_round1_spectrin.hdf5")
    path_b = os.path.join(folder, f"{stem}_round2_adducin.hdf5")
    _write(path_a, np.concatenate([fa, ma[0]]), np.concatenate([xa, ma[1]]),
           np.concatenate([ya, ma[2]]), np.concatenate([za, ma[3]]), rng)
    _write(path_b, np.concatenate([fb, mb[0]]), np.concatenate([xb, mb[1]]),
           np.concatenate([yb, mb[2]]), np.concatenate([zb, mb[3]]), rng)
    return SyntheticPair(
        path_a=path_a, path_b=path_b, centre_nm=centre,
        ring_radius_nm=radius, period_nm=period, phase=phase,
        shift_nm=(float(shift[0]), float(shift[1]), float(shift[2])),
        marker_error_nm=marker_error_nm,
    )


# ---------------------------------------------------------------------------
# In memory, with the ground truth attached
# ---------------------------------------------------------------------------
#
# write_pair above exists to test the FILE path: loading, markers, the
# registration. What it cannot do is say what the transverse numbers
# should come out as, because it never hands back where it put the
# clusters. This does: every channel comes back with the true centre of
# every cluster, so a validator can compute the right answer on the truth
# with its own independent code and compare the pipeline's answer to it.
#
# The model is the same one: rings of isotropic Gaussian clusters, stacked
# along z with the MPS period, the partner ``phase`` of a period away.
# What can now be varied is everything a transverse measure depends on --
# the partner's angular offset, its radius, which positions it occupies,
# how densely each cluster is sampled -- because each of those has an
# answer that can be written down before anything is measured.


@dataclass
class RingTruth:
    """Where one synthetic channel's clusters really are."""

    # (n, 2) true cluster centres in the plane, in increasing angle: the
    # order a contour through them has to follow.
    centres_nm: np.ndarray
    # The true angle of each, radians.
    angles: np.ndarray
    radius_nm: float
    sigma_xy_nm: float
    # Localizations drawn per cluster in the ring at the axial peak.
    n_per_cluster: int


@dataclass
class SyntheticChannels:
    """Two channels in nanometres, already in one frame, and the truth."""

    x_a: np.ndarray
    y_a: np.ndarray
    z_a: np.ndarray
    x_b: np.ndarray
    y_b: np.ndarray
    z_b: np.ndarray
    truth_a: RingTruth
    truth_b: RingTruth
    centre_nm: Tuple[float, float]
    period_nm: float
    phase: float


def _ring_channel(rng: np.random.Generator, centre: Tuple[float, float], *,
                  n_clusters: int, radius: float, angle_offset: float,
                  jitter: float, occupied: Optional[np.ndarray],
                  n_per_cluster: int, sigma_xy: float, sigma_z: float,
                  period: float, z_offset: float, n_rings: int,
                  ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, RingTruth]:
    """One channel: ``n_rings`` rings along z; the truth of the middle one.

    The middle ring (k = 0) sits at ``z_offset`` and holds
    ``n_per_cluster`` localizations per cluster; the others hold half, as
    a section cut through the middle ring's centre would.
    """
    keep = (np.ones(n_clusters, dtype=bool) if occupied is None
            else np.asarray(occupied, dtype=bool))
    xs, ys, zs = [], [], []
    truth_angles = np.empty(0)
    half = n_rings // 2
    for k in range(-half, half + 1):
        angles = angle_offset + np.linspace(0, 2 * np.pi, n_clusters,
                                            endpoint=False)
        if jitter:
            angles = angles + rng.normal(0, jitter, angles.size)
        angles = angles[keep]
        n = n_per_cluster if k == 0 else max(1, n_per_cluster // 2)
        for angle in angles:
            cx = centre[0] + radius * np.cos(angle)
            cy = centre[1] + radius * np.sin(angle)
            xs.append(cx + rng.normal(0, sigma_xy, n))
            ys.append(cy + rng.normal(0, sigma_xy, n))
            zs.append(k * period + z_offset + rng.normal(0, sigma_z, n))
        if k == 0:
            truth_angles = np.asarray(angles, dtype=float)
    order = np.argsort(np.mod(truth_angles, 2 * np.pi))
    truth_angles = truth_angles[order]
    centres = np.column_stack([centre[0] + radius * np.cos(truth_angles),
                               centre[1] + radius * np.sin(truth_angles)])
    truth = RingTruth(centres_nm=centres, angles=truth_angles,
                      radius_nm=float(radius), sigma_xy_nm=float(sigma_xy),
                      n_per_cluster=int(n_per_cluster))
    return (np.concatenate(xs), np.concatenate(ys), np.concatenate(zs),
            truth)


def ring_pair(
    seed: int = 0,
    *,
    n_clusters: int = 16,
    radius_nm: float = 400.0,
    radius_b_nm: Optional[float] = None,
    angle_offset_b: float = 0.0,
    occupied_b: Optional[np.ndarray] = None,
    phase: float = 0.0,
    n_per_cluster: int = 60,
    n_per_cluster_b: Optional[int] = None,
    sigma_xy_nm: float = 8.0,
    sigma_z_nm: float = 25.0,
    angular_jitter: float = 0.05,
    period_nm: float = 190.0,
    n_rings: int = 3,
    b_is_a: bool = False,
) -> SyntheticChannels:
    """
    Two channels around one axon, in memory, with the truth attached.

    Parameters
    ----------
    radius_b_nm : the partner's ring radius; None is spectrin's.
    angle_offset_b : the partner's angular offset from spectrin, radians.
        Half the spacing (pi / n_clusters) interleaves the two rings.
    occupied_b : which of the n_clusters positions the partner occupies.
    phase : the partner's axial offset as a fraction of the period.
    n_per_cluster_b : localizations per partner cluster; None is
        spectrin's. Ten times more is how a channel oversampled per
        resolution cell, as the real adducin files are, is modelled.
    angular_jitter : per-cluster angular scatter, radians, drawn
        independently for each channel. 0 makes every answer analytic.
    b_is_a : the partner IS spectrin, localization for localization.
        Every cross-channel number then has an exact answer -- the whole
        ring shared, zero distance, zero offset -- which is the sharpest
        test there is of whether the arithmetic is right.
    """
    rng = np.random.default_rng(seed)
    centre = (16000.0, 16000.0)
    xa, ya, za, truth_a = _ring_channel(
        rng, centre, n_clusters=n_clusters, radius=radius_nm,
        angle_offset=0.0, jitter=angular_jitter, occupied=None,
        n_per_cluster=n_per_cluster, sigma_xy=sigma_xy_nm,
        sigma_z=sigma_z_nm, period=period_nm, z_offset=0.0, n_rings=n_rings)
    if b_is_a:
        return SyntheticChannels(
            x_a=xa, y_a=ya, z_a=za, x_b=xa.copy(), y_b=ya.copy(),
            z_b=za.copy(), truth_a=truth_a, truth_b=truth_a,
            centre_nm=centre, period_nm=period_nm, phase=0.0)
    xb, yb, zb, truth_b = _ring_channel(
        rng, centre, n_clusters=n_clusters,
        radius=radius_nm if radius_b_nm is None else radius_b_nm,
        angle_offset=angle_offset_b, jitter=angular_jitter,
        occupied=occupied_b,
        n_per_cluster=(n_per_cluster if n_per_cluster_b is None
                       else n_per_cluster_b),
        sigma_xy=sigma_xy_nm, sigma_z=sigma_z_nm, period=period_nm,
        z_offset=phase * period_nm, n_rings=n_rings)
    return SyntheticChannels(
        x_a=xa, y_a=ya, z_a=za, x_b=xb, y_b=yb, z_b=zb,
        truth_a=truth_a, truth_b=truth_b, centre_nm=centre,
        period_nm=period_nm, phase=phase)
